wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.32504753320393287
learning_rate:
  value: 7.299696931651505e-05
length_penalty:
  value: 0.3653141491273249
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 8
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 64
target_modules:
  value: q_proj,v_proj,k_proj,out_proj,fc1,fc2
warmup_steps:
  value: 500
