wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.7342567884468886
learning_rate:
  value: 7.891361068445248e-06
length_penalty:
  value: 2.3333574000928836
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 10
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 128
target_modules:
  value: q_proj,v_proj,k_proj,out_proj
warmup_steps:
  value: 0
