wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.5879344866147174
learning_rate:
  value: 9.657118364579022e-05
length_penalty:
  value: 9.982879151413131
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 9
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 8
target_modules:
  value: q_proj,v_proj,k_proj,out_proj,fc1,fc2
warmup_steps:
  value: 1000
