wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.1721324706606785
learning_rate:
  value: 7.075474978008953e-06
length_penalty:
  value: 6.423089519418314
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 1
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 64
target_modules:
  value: q_proj,v_proj,k_proj
warmup_steps:
  value: 250
