wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.33899904758648225
learning_rate:
  value: 8.605739317007502e-05
length_penalty:
  value: 3.373256094780462
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 5
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 8
target_modules:
  value: q_proj,v_proj,k_proj,out_proj
warmup_steps:
  value: 100
