wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.4773770302132168
learning_rate:
  value: 1.3584892307988038e-05
length_penalty:
  value: 3.722985860642192
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 4
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 16
target_modules:
  value: q_proj,v_proj
warmup_steps:
  value: 250
