wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.25911102722079615
learning_rate:
  value: 9.09772001360525e-05
length_penalty:
  value: 6.917282454055097
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 5
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 128
target_modules:
  value: q_proj,v_proj,k_proj
warmup_steps:
  value: 0
