wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.5294667003379896
learning_rate:
  value: 6.860680452301991e-05
length_penalty:
  value: 7.87261491748588
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 1
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 16
target_modules:
  value: q_proj,v_proj,k_proj
warmup_steps:
  value: 100
