wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.43605356808512846
learning_rate:
  value: 4.3109248640282154e-05
length_penalty:
  value: 7.505812763721259
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 1
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 8
target_modules:
  value: q_proj,v_proj,k_proj
warmup_steps:
  value: 750
