wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.4226571060187128
learning_rate:
  value: 9.459452545789064e-05
length_penalty:
  value: 1.4959363508949186
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 10
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 32
target_modules:
  value: q_proj,v_proj,k_proj,out_proj,fc1,fc2
warmup_steps:
  value: 0
