wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.2325526057853522
learning_rate:
  value: 5.882697412929134e-05
length_penalty:
  value: 1.184454341243143
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 2
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 8
target_modules:
  value: q_proj,v_proj,k_proj
warmup_steps:
  value: 100
