wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.0789450619432559
learning_rate:
  value: 3.866088055813584e-05
length_penalty:
  value: 3.089764747681516
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 8
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 64
target_modules:
  value: q_proj,v_proj,k_proj
warmup_steps:
  value: 250
