wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.6048845120546729
learning_rate:
  value: 9.12011380228968e-05
length_penalty:
  value: 3.490736319677329
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 5
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 64
target_modules:
  value: q_proj,v_proj,k_proj,out_proj,fc1,fc2
warmup_steps:
  value: 500
