wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.4270170524066644
learning_rate:
  value: 4.990098964021203e-05
length_penalty:
  value: 3.4667945565877156
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 7
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 8
target_modules:
  value: q_proj,v_proj
warmup_steps:
  value: 100
