wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.7951110734749816
learning_rate:
  value: 5.566276887344448e-06
length_penalty:
  value: 0.14118601225266425
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 9
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 16
target_modules:
  value: q_proj,v_proj,k_proj
warmup_steps:
  value: 750
