wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.4834741233033806
learning_rate:
  value: 5.100903513820392e-05
length_penalty:
  value: 7.466040368334193
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 7
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 32
target_modules:
  value: q_proj,v_proj,k_proj,out_proj
warmup_steps:
  value: 250
