wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.7819703825962736
learning_rate:
  value: 4.4276454316241915e-05
length_penalty:
  value: 4.059275633782669
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 4
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 128
target_modules:
  value: q_proj,v_proj,k_proj
warmup_steps:
  value: 1000
