wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.1955135311371608
learning_rate:
  value: 6.612227093673773e-06
length_penalty:
  value: 1.624610668915234
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 10
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 64
target_modules:
  value: q_proj,v_proj
warmup_steps:
  value: 0
