wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.09584712414049967
learning_rate:
  value: 8.792405803842913e-05
length_penalty:
  value: 7.740808912938969
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 8
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 8
target_modules:
  value: q_proj,v_proj
warmup_steps:
  value: 500
