wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.7405680661281676
learning_rate:
  value: 3.2536500333035394e-05
length_penalty:
  value: 4.512316993146306
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 2
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 32
target_modules:
  value: q_proj,v_proj,k_proj
warmup_steps:
  value: 100
