wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.14702695425288806
learning_rate:
  value: 2.984659357571304e-05
length_penalty:
  value: 9.90827656377684
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 6
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 64
target_modules:
  value: q_proj,v_proj,k_proj,out_proj
warmup_steps:
  value: 500
