wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.5202729913776714
learning_rate:
  value: 6.474124171250508e-05
length_penalty:
  value: 6.867276568753819
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 4
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 128
target_modules:
  value: q_proj,v_proj,k_proj,out_proj
warmup_steps:
  value: 0
