wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.0718643927395994
learning_rate:
  value: 2.9343337866334513e-05
length_penalty:
  value: 4.371725226888382
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 6
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 64
target_modules:
  value: q_proj,v_proj,k_proj,out_proj
warmup_steps:
  value: 500
