wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.489901415075691
learning_rate:
  value: 3.9799102849008427e-05
length_penalty:
  value: 8.670601856323797
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 6
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 64
target_modules:
  value: q_proj,v_proj,k_proj,out_proj,fc1,fc2
warmup_steps:
  value: 0
