wandb_version: 1

alpha_multiplier:
  value: 1
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.34227535310127827
learning_rate:
  value: 6.443535530633893e-05
length_penalty:
  value: 1.889517023661483
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 7
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 64
target_modules:
  value: q_proj,v_proj
warmup_steps:
  value: 750
