wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.7532114914827235
learning_rate:
  value: 5.736568488878264e-05
length_penalty:
  value: 2.201356989510149
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 5
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 8
target_modules:
  value: q_proj,v_proj
warmup_steps:
  value: 500
