wandb_version: 1

alpha_multiplier:
  value: 2
data_file:
  value: /n/holylabs/LABS/arielpro_lab/Lab/michaelzhao/new_training_data.csv
dropout:
  value: 0.7164686140888792
learning_rate:
  value: 7.722170912010442e-05
length_penalty:
  value: 3.770034053982878
model_name:
  value: facebook/bart-large-cnn
num_train_epochs:
  value: 2
output_dir:
  value: ./lora_bart_subtopics_sweep
r:
  value: 16
target_modules:
  value: q_proj,v_proj,k_proj,out_proj
warmup_steps:
  value: 250
